export type GlobalScenario = {
  id:string
  region:string
  title:string
  channel:string
  action_type:string
  message:string
  expected_scam_type:string
  expected_risk_level:string
  global_relevance:string
}

export const globalScenarios:GlobalScenario[] = [
  {
    id:'br-fake-child-pix',
    region:'Brasil',
    title:'Falso filho pedindo Pix',
    channel:'whatsapp',
    action_type:'pix',
    message:'Cenario educativo simulado: pessoa diz ser familiar, usa numero novo e pede Pix urgente.',
    expected_scam_type:'falso familiar pedindo Pix',
    expected_risk_level:'critical',
    global_relevance:'Representa pedidos financeiros urgentes com identidade familiar nao verificada.',
  },
  {
    id:'br-fake-bank-link',
    region:'Brasil',
    title:'Falso banco com link',
    channel:'sms',
    action_type:'link',
    message:'Cenario educativo simulado: alerta bancario pede clique em link para atualizar cadastro.',
    expected_scam_type:'falso banco com link',
    expected_risk_level:'high',
    global_relevance:'Links bancarios suspeitos existem em varios paises e exigem verificacao oficial.',
  },
  {
    id:'br-boleto-scam',
    region:'Brasil',
    title:'Golpe de boleto',
    channel:'email',
    action_type:'pix',
    message:'Cenario educativo simulado: boleto ou cobranca inesperada pressiona pagamento imediato.',
    expected_scam_type:'cobranca falsa',
    expected_risk_level:'high',
    global_relevance:'Cobrancas falsas variam por mercado, mas usam pressao financeira parecida.',
  },
  {
    id:'br-delivery-scam',
    region:'Brasil',
    title:'Golpe de entrega',
    channel:'sms',
    action_type:'link',
    message:'Cenario educativo simulado: entrega pendente pede taxa pequena ou atualizacao de endereco.',
    expected_scam_type:'falsa entrega',
    expected_risk_level:'medium',
    global_relevance:'Falsas entregas usam marcas conhecidas e urgencia logistica no mundo todo.',
  },
  {
    id:'us-gift-card',
    region:'United States',
    title:'Gift card scam',
    channel:'phone',
    action_type:'pix',
    message:'Simulated educational scenario: caller pressures the user to buy gift cards to resolve an urgent issue.',
    expected_scam_type:'gift card payment pressure',
    expected_risk_level:'critical',
    global_relevance:'Alternative payment rails still follow the same pattern: pressure plus unverified authority.',
  },
  {
    id:'us-fake-tech-support',
    region:'United States',
    title:'Fake tech support',
    channel:'browser popup',
    action_type:'app',
    message:'Simulated educational scenario: fake support asks the user to install remote access software.',
    expected_scam_type:'fake technical support',
    expected_risk_level:'critical',
    global_relevance:'Remote access requests are sensitive globally and should trigger a protective pause.',
  },
  {
    id:'us-banking-phishing',
    region:'United States',
    title:'Banking phishing',
    channel:'email',
    action_type:'link',
    message:'Simulated educational scenario: bank-branded message asks the user to verify an account through a link.',
    expected_scam_type:'banking phishing',
    expected_risk_level:'high',
    global_relevance:'Bank impersonation is globally relevant across different institutions and languages.',
  },
  {
    id:'us-tax-scam',
    region:'United States',
    title:'IRS/tax scam',
    channel:'phone',
    action_type:'pix',
    message:'Simulated educational scenario: supposed tax authority demands fast payment to avoid a penalty.',
    expected_scam_type:'fake tax authority pressure',
    expected_risk_level:'high',
    global_relevance:'Tax authority impersonation maps to local government agencies in many countries.',
  },
  {
    id:'us-romance-scam',
    region:'United States',
    title:'Romance scam',
    channel:'social media',
    action_type:'pix',
    message:'Simulated educational scenario: online relationship asks for urgent financial help before identity is verified.',
    expected_scam_type:'romance financial manipulation',
    expected_risk_level:'high',
    global_relevance:'Emotional trust and financial pressure are universal manipulation patterns.',
  },
  {
    id:'eu-banking-phishing',
    region:'Europe',
    title:'Banking phishing',
    channel:'email',
    action_type:'link',
    message:'Simulated educational scenario: bank message asks for urgent identity confirmation through a link.',
    expected_scam_type:'banking phishing',
    expected_risk_level:'high',
    global_relevance:'Banking verification scams adapt to local banks and regulations.',
  },
  {
    id:'eu-fake-delivery',
    region:'Europe',
    title:'Fake delivery',
    channel:'sms',
    action_type:'link',
    message:'Simulated educational scenario: parcel notice asks for a small fee through a suspicious link.',
    expected_scam_type:'fake delivery fee',
    expected_risk_level:'medium',
    global_relevance:'Delivery scams are common where e-commerce adoption is high.',
  },
  {
    id:'eu-fake-government-fine',
    region:'Europe',
    title:'Fake government fine',
    channel:'email',
    action_type:'pix',
    message:'Simulated educational scenario: official-looking notice pressures immediate fine payment.',
    expected_scam_type:'false authority payment request',
    expected_risk_level:'high',
    global_relevance:'False authority works across countries but must be adapted to local channels.',
  },
  {
    id:'eu-investment-scam',
    region:'Europe',
    title:'Investment scam',
    channel:'social media',
    action_type:'document',
    message:'Simulated educational scenario: investment offer asks for documents and a quick deposit.',
    expected_scam_type:'investment manipulation',
    expected_risk_level:'high',
    global_relevance:'Investment pressure combines financial urgency with document risk.',
  },
  {
    id:'in-upi-like-payment',
    region:'India',
    title:'UPI-like payment scam',
    channel:'messaging app',
    action_type:'pix',
    message:'Simulated educational scenario: payment request pushes the user to approve a transfer quickly.',
    expected_scam_type:'instant payment pressure',
    expected_risk_level:'critical',
    global_relevance:'Instant-payment systems vary by country, but risky approval pressure is global.',
  },
  {
    id:'in-fake-kyc',
    region:'India',
    title:'Fake KYC update',
    channel:'sms',
    action_type:'document',
    message:'Simulated educational scenario: account update request asks for identity documents through a link.',
    expected_scam_type:'fake KYC update',
    expected_risk_level:'high',
    global_relevance:'Identity verification pressure maps to many regulated markets.',
  },
  {
    id:'in-otp-code',
    region:'India',
    title:'OTP/SMS code scam',
    channel:'phone',
    action_type:'sms_code',
    message:'Simulated educational scenario: caller asks for a one-time code to fix an account issue.',
    expected_scam_type:'OTP code request',
    expected_risk_level:'critical',
    global_relevance:'One-time code requests are dangerous across banks, wallets and platforms.',
  },
  {
    id:'af-mobile-money',
    region:'Africa',
    title:'Mobile money transfer scam',
    channel:'sms',
    action_type:'pix',
    message:'Simulated educational scenario: message pressures a mobile money transfer to an unverified contact.',
    expected_scam_type:'mobile money transfer pressure',
    expected_risk_level:'critical',
    global_relevance:'Mobile money rails need the same pre-damage pause as Pix or UPI-like systems.',
  },
  {
    id:'af-fake-support-agent',
    region:'Africa',
    title:'Fake support agent',
    channel:'phone',
    action_type:'password',
    message:'Simulated educational scenario: supposed support agent asks for account access details.',
    expected_scam_type:'fake support credential request',
    expected_risk_level:'critical',
    global_relevance:'Support impersonation is a cross-market risk for financial and telecom accounts.',
  },
  {
    id:'af-account-verification',
    region:'Africa',
    title:'Account verification scam',
    channel:'messaging app',
    action_type:'document',
    message:'Simulated educational scenario: account warning asks the user to send documents quickly.',
    expected_scam_type:'false account verification',
    expected_risk_level:'high',
    global_relevance:'Verification pressure appears wherever digital identity is used.',
  },
  {
    id:'global-password-request',
    region:'Global',
    title:'Pedido de senha',
    channel:'messaging app',
    action_type:'password',
    message:'Cenario educativo simulado: alguem pede senha ou acesso para resolver uma urgencia.',
    expected_scam_type:'pedido de credencial',
    expected_risk_level:'critical',
    global_relevance:'Senhas nunca devem ser compartilhadas por mensagem, em qualquer mercado.',
  },
  {
    id:'global-code-request',
    region:'Global',
    title:'Pedido de codigo',
    channel:'phone',
    action_type:'sms_code',
    message:'Cenario educativo simulado: contato pede codigo de autenticacao recebido por SMS.',
    expected_scam_type:'pedido de codigo de autenticacao',
    expected_risk_level:'critical',
    global_relevance:'Codigos de autenticacao sao chaves de acesso em praticamente todos os paises.',
  },
  {
    id:'global-fake-job-fee',
    region:'Global',
    title:'Falso emprego com taxa',
    channel:'messaging app',
    action_type:'pix',
    message:'Cenario educativo simulado: vaga promete oportunidade, mas exige taxa antecipada.',
    expected_scam_type:'falso emprego pedindo taxa',
    expected_risk_level:'high',
    global_relevance:'A promessa de oportunidade com pagamento antecipado aparece em varios mercados.',
  },
  {
    id:'global-document-scam',
    region:'Global',
    title:'Golpe de documento',
    channel:'email',
    action_type:'document',
    message:'Cenario educativo simulado: pedido urgente solicita envio de documento pessoal.',
    expected_scam_type:'pedido de documento sensivel',
    expected_risk_level:'high',
    global_relevance:'Documentos pessoais exigem verificacao de finalidade e canal oficial.',
  },
  {
    id:'global-marketplace-scam',
    region:'Global',
    title:'Golpe de marketplace',
    channel:'marketplace chat',
    action_type:'link',
    message:'Cenario educativo simulado: comprador ou vendedor tenta levar a conversa para link externo.',
    expected_scam_type:'marketplace link externo',
    expected_risk_level:'medium',
    global_relevance:'Marketplaces globais enfrentam risco quando a verificacao sai da plataforma.',
  },
]

export const globalApplicabilityRegions = [
  {
    region:'Brasil',
    focus:'Pix + WhatsApp scams',
    description:'Falso familiar, boleto, entrega e link bancario com pressao de pagamento imediato.',
  },
  {
    region:'United States',
    focus:'gift cards + fake tech support',
    description:'Pagamentos alternativos, suporte falso, romance scam e impersonificacao de autoridade.',
  },
  {
    region:'Europe',
    focus:'banking phishing + delivery scams',
    description:'Bancos, entregas, multas falsas e investimento com regras locais de compliance.',
  },
  {
    region:'India',
    focus:'UPI/OTP/KYC scams',
    description:'Pagamentos instantaneos, pedidos de OTP e atualizacoes falsas de identidade.',
  },
  {
    region:'Africa',
    focus:'mobile money scams',
    description:'Transferencias de mobile money, suporte falso e verificacao de conta.',
  },
  {
    region:'Global',
    focus:'credentials, links, documents, remote access apps',
    description:'Acoes sensiveis que exigem pausa protetiva antes do dano.',
  },
]

export const globalThreatPatterns = [
  'urgency',
  'fear',
  'false authority',
  'fake family identity',
  'isolation',
  'financial pressure',
  'credential request',
  'document request',
  'remote access request',
  'OTP/code request',
]
