export type GlobalScenario = {
  id:string
  region:string
  title:string
  channel:string
  action_type:string
  message:string
  expected_scam_type:string
  expected_risk_level:string
  global_relevance:string
  recommended_action:string
}

export const globalScenarios:GlobalScenario[] = [
  {
    id:'br-fake-child-pix',
    region:'Brasil',
    title:'Falso filho pedindo Pix',
    channel:'whatsapp',
    action_type:'pix',
    message:'Cenário educativo simulado: pessoa diz ser familiar, usa número novo e pede Pix urgente.',
    expected_scam_type:'falso familiar pedindo Pix',
    expected_risk_level:'critical',
    global_relevance:'Representa pedidos financeiros urgentes com identidade familiar não verificada.',
    recommended_action:'Pausar Pix, confirmar por ligação no contato salvo e acionar Trust Lock.',
  },
  {
    id:'br-fake-bank-link',
    region:'Brasil',
    title:'Falso banco com link',
    channel:'sms',
    action_type:'link',
    message:'Cenário educativo simulado: alerta bancário pede clique em link para atualizar cadastro.',
    expected_scam_type:'falso banco com link',
    expected_risk_level:'high',
    global_relevance:'Links bancários suspeitos existem em vários países e exigem verificação oficial.',
    recommended_action:'Não clicar; abrir o app do banco manualmente ou ligar para o número oficial.',
  },
  {
    id:'br-boleto-scam',
    region:'Brasil',
    title:'Golpe de boleto',
    channel:'email',
    action_type:'pix',
    message:'Cenário educativo simulado: boleto ou cobrança inesperada pressiona pagamento imediato.',
    expected_scam_type:'cobrança falsa',
    expected_risk_level:'high',
    global_relevance:'Cobranças falsas variam por mercado, mas usam pressão financeira parecida.',
    recommended_action:'Validar cobrança no canal oficial antes de qualquer pagamento.',
  },
  {
    id:'br-delivery-scam',
    region:'Brasil',
    title:'Golpe de entrega',
    channel:'sms',
    action_type:'link',
    message:'Cenário educativo simulado: entrega pendente pede taxa pequena ou atualização de endereço.',
    expected_scam_type:'falsa entrega',
    expected_risk_level:'medium',
    global_relevance:'Falsas entregas usam marcas conhecidas e urgência logística no mundo todo.',
    recommended_action:'Conferir rastreio no site oficial da transportadora, sem links da mensagem.',
  },
  {
    id:'us-gift-card',
    region:'Estados Unidos',
    title:'Golpe de vale-presente',
    channel:'telefone',
    action_type:'pix',
    message:'Cenário educativo simulado: ligação pressiona a compra de vales-presente para resolver um problema urgente.',
    expected_scam_type:'pressão por pagamento em vale-presente',
    expected_risk_level:'critical',
    global_relevance:'Meios de pagamento alternativos seguem o mesmo padrão: pressão e autoridade não verificada.',
    recommended_action:'Encerrar contato, não comprar vales e reportar ao canal oficial.',
  },
  {
    id:'us-fake-tech-support',
    region:'Estados Unidos',
    title:'Falso suporte técnico',
    channel:'pop-up do navegador',
    action_type:'app',
    message:'Cenário educativo simulado: suporte falso pede instalação de software de acesso remoto.',
    expected_scam_type:'falso suporte técnico',
    expected_risk_level:'critical',
    global_relevance:'Pedidos de acesso remoto são sensíveis globalmente e devem acionar pausa protetiva.',
    recommended_action:'Fechar pop-up, não instalar app remoto e revisar dispositivo com suporte oficial.',
  },
  {
    id:'us-banking-phishing',
    region:'Estados Unidos',
    title:'Phishing bancário',
    channel:'email',
    action_type:'link',
    message:'Cenário educativo simulado: mensagem com marca de banco pede verificação de conta por link.',
    expected_scam_type:'phishing bancário',
    expected_risk_level:'high',
    global_relevance:'Imitação de banco é relevante em vários idiomas e instituições.',
    recommended_action:'Acessar o banco somente pelo app ou site digitado manualmente.',
  },
  {
    id:'us-tax-scam',
    region:'Estados Unidos',
    title:'Golpe de imposto/autoridade',
    channel:'telefone',
    action_type:'pix',
    message:'Cenário educativo simulado: suposta autoridade fiscal exige pagamento rápido para evitar multa.',
    expected_scam_type:'falsa autoridade fiscal',
    expected_risk_level:'high',
    global_relevance:'Imitação de órgão público mapeia para agências locais em vários países.',
    recommended_action:'Não pagar sob pressão; confirmar em canal governamental oficial.',
  },
  {
    id:'us-romance-scam',
    region:'Estados Unidos',
    title:'Golpe de romance',
    channel:'rede social',
    action_type:'pix',
    message:'Cenário educativo simulado: relação online pede ajuda financeira urgente antes de verificar identidade.',
    expected_scam_type:'manipulação financeira por confiança',
    expected_risk_level:'high',
    global_relevance:'Confiança emocional e pressão financeira são padrões universais de manipulação.',
    recommended_action:'Pausar transferência e validar identidade por canal independente.',
  },
  {
    id:'eu-banking-phishing',
    region:'Europa',
    title:'Phishing bancário',
    channel:'email',
    action_type:'link',
    message:'Cenário educativo simulado: mensagem bancária pede confirmação urgente de identidade por link.',
    expected_scam_type:'phishing bancário',
    expected_risk_level:'high',
    global_relevance:'Golpes de verificação bancária se adaptam a bancos e regras locais.',
    recommended_action:'Ignorar link e usar app ou site oficial do banco.',
  },
  {
    id:'eu-fake-delivery',
    region:'Europa',
    title:'Falsa entrega',
    channel:'sms',
    action_type:'link',
    message:'Cenário educativo simulado: aviso de encomenda pede taxa pequena por link suspeito.',
    expected_scam_type:'taxa falsa de entrega',
    expected_risk_level:'medium',
    global_relevance:'Golpes de entrega são comuns onde o e-commerce é alto.',
    recommended_action:'Verificar encomenda no portal oficial da transportadora.',
  },
  {
    id:'eu-fake-government-fine',
    region:'Europa',
    title:'Multa governamental falsa',
    channel:'email',
    action_type:'pix',
    message:'Cenário educativo simulado: aviso com aparência oficial pressiona pagamento imediato de multa.',
    expected_scam_type:'pedido de pagamento com falsa autoridade',
    expected_risk_level:'high',
    global_relevance:'Falsa autoridade funciona em vários países, mas exige adaptação de canal.',
    recommended_action:'Confirmar multa apenas em portal ou canal governamental verificado.',
  },
  {
    id:'eu-investment-scam',
    region:'Europa',
    title:'Golpe de investimento',
    channel:'rede social',
    action_type:'document',
    message:'Cenário educativo simulado: oferta de investimento pede documentos e depósito rápido.',
    expected_scam_type:'manipulação de investimento',
    expected_risk_level:'high',
    global_relevance:'Pressão de investimento combina urgência financeira com risco de documento.',
    recommended_action:'Não enviar documentos; validar oferta com instituição regulada.',
  },
  {
    id:'in-upi-like-payment',
    region:'Índia',
    title:'Golpe de pagamento instantâneo',
    channel:'app de mensagem',
    action_type:'pix',
    message:'Cenário educativo simulado: pedido de pagamento pressiona aprovação rápida de transferência.',
    expected_scam_type:'pressão em pagamento instantâneo',
    expected_risk_level:'critical',
    global_relevance:'Sistemas de pagamento instantâneo variam por país, mas a pressão de aprovação é global.',
    recommended_action:'Revisar destinatário e valor antes de aprovar qualquer transferência.',
  },
  {
    id:'in-fake-kyc',
    region:'Índia',
    title:'Atualização KYC falsa',
    channel:'sms',
    action_type:'document',
    message:'Cenário educativo simulado: pedido de atualização de conta solicita documentos por link.',
    expected_scam_type:'atualização KYC falsa',
    expected_risk_level:'high',
    global_relevance:'Pressão de verificação de identidade aparece em mercados regulados.',
    recommended_action:'Atualizar cadastro apenas no app ou site oficial da instituição.',
  },
  {
    id:'in-otp-code',
    region:'Índia',
    title:'Golpe de código SMS/OTP',
    channel:'telefone',
    action_type:'sms_code',
    message:'Cenário educativo simulado: ligação pede código de uso único para corrigir conta.',
    expected_scam_type:'pedido de código OTP',
    expected_risk_level:'critical',
    global_relevance:'Pedidos de código de uso único são perigosos em bancos, carteiras e plataformas.',
    recommended_action:'Nunca compartilhar OTP; encerrar ligação e avisar instituição.',
  },
  {
    id:'af-mobile-money',
    region:'África',
    title:'Golpe de transferência móvel',
    channel:'sms',
    action_type:'pix',
    message:'Cenário educativo simulado: mensagem pressiona transferência mobile money para contato não verificado.',
    expected_scam_type:'pressão em transferência mobile money',
    expected_risk_level:'critical',
    global_relevance:'Mobile money exige a mesma pausa pré-dano que Pix ou pagamentos instantâneos.',
    recommended_action:'Pausar transferência e confirmar identidade do destinatário.',
  },
  {
    id:'af-fake-support-agent',
    region:'África',
    title:'Agente de suporte falso',
    channel:'telefone',
    action_type:'password',
    message:'Cenário educativo simulado: suposto suporte pede dados de acesso à conta.',
    expected_scam_type:'pedido de credencial por suporte falso',
    expected_risk_level:'critical',
    global_relevance:'Imitação de suporte é risco transversal em contas financeiras e telecom.',
    recommended_action:'Não informar senha; ligar para número oficial da operadora ou banco.',
  },
  {
    id:'af-account-verification',
    region:'África',
    title:'Verificação de conta falsa',
    channel:'app de mensagem',
    action_type:'document',
    message:'Cenário educativo simulado: alerta de conta pede envio rápido de documentos.',
    expected_scam_type:'verificação de conta falsa',
    expected_risk_level:'high',
    global_relevance:'Pressão de verificação aparece onde identidade digital é usada.',
    recommended_action:'Enviar documentos somente por canal autenticado da instituição.',
  },
  {
    id:'global-password-request',
    region:'Global',
    title:'Pedido de senha',
    channel:'app de mensagem',
    action_type:'password',
    message:'Cenário educativo simulado: alguém pede senha ou acesso para resolver uma urgência.',
    expected_scam_type:'pedido de credencial',
    expected_risk_level:'critical',
    global_relevance:'Senhas nunca devem ser compartilhadas por mensagem, em qualquer mercado.',
    recommended_action:'Recusar pedido e alterar senha se houver qualquer dúvida.',
  },
  {
    id:'global-code-request',
    region:'Global',
    title:'Pedido de código',
    channel:'telefone',
    action_type:'sms_code',
    message:'Cenário educativo simulado: contato pede código de autenticação recebido por SMS.',
    expected_scam_type:'pedido de código de autenticação',
    expected_risk_level:'critical',
    global_relevance:'Códigos de autenticação são chaves de acesso em praticamente todos os países.',
    recommended_action:'Não repassar código; acionar Trust Lock e contato de confiança.',
  },
  {
    id:'global-fake-job-fee',
    region:'Global',
    title:'Falso emprego com taxa',
    channel:'app de mensagem',
    action_type:'pix',
    message:'Cenário educativo simulado: vaga promete oportunidade, mas exige taxa antecipada.',
    expected_scam_type:'falso emprego pedindo taxa',
    expected_risk_level:'high',
    global_relevance:'Promessa de oportunidade com pagamento antecipado aparece em vários mercados.',
    recommended_action:'Não pagar taxa antecipada; validar empresa por canal independente.',
  },
  {
    id:'global-document-scam',
    region:'Global',
    title:'Golpe de documento',
    channel:'email',
    action_type:'document',
    message:'Cenário educativo simulado: pedido urgente solicita envio de documento pessoal.',
    expected_scam_type:'pedido de documento sensível',
    expected_risk_level:'high',
    global_relevance:'Documentos pessoais exigem verificação de finalidade e canal oficial.',
    recommended_action:'Confirmar finalidade e canal antes de enviar qualquer documento.',
  },
  {
    id:'global-marketplace-scam',
    region:'Global',
    title:'Golpe de marketplace',
    channel:'chat de marketplace',
    action_type:'link',
    message:'Cenário educativo simulado: comprador ou vendedor tenta levar a conversa para link externo.',
    expected_scam_type:'link externo em marketplace',
    expected_risk_level:'medium',
    global_relevance:'Marketplaces globais enfrentam risco quando a verificação sai da plataforma.',
    recommended_action:'Manter negociação dentro da plataforma e recusar links externos.',
  },
]

export const globalApplicabilityRegions = [
  {
    region:'Brasil',
    focus:'Pix + golpes no WhatsApp',
    description:'Falso familiar, boleto, entrega e link bancário com pressão de pagamento imediato.',
  },
  {
    region:'Estados Unidos',
    focus:'vales-presente + falso suporte técnico',
    description:'Pagamentos alternativos, suporte falso, golpe de romance e imitação de autoridade.',
  },
  {
    region:'Europa',
    focus:'phishing bancário + falsas entregas',
    description:'Bancos, entregas, multas falsas e investimento com regras locais de compliance.',
  },
  {
    region:'Índia',
    focus:'pagamento instantâneo / OTP / KYC',
    description:'Aprovações instantâneas, pedidos de OTP e atualizações falsas de identidade.',
  },
  {
    region:'África',
    focus:'mobile money e suporte falso',
    description:'Transferências mobile money, suporte falso e verificação de conta.',
  },
  {
    region:'Global',
    focus:'credenciais, links, documentos e apps remotos',
    description:'Ações sensíveis que exigem pausa protetiva antes do dano.',
  },
]

export const globalThreatPatternGroups = [
  {
    title:'Pressão emocional',
    items:['Urgência', 'Medo/pressão', 'Isolamento', 'Pressão financeira'],
  },
  {
    title:'Identidade falsa',
    items:['Falsa autoridade', 'Falsa identidade familiar'],
  },
  {
    title:'Pedido financeiro',
    items:['Pressão financeira', 'Transferência urgente'],
  },
  {
    title:'Credenciais e acesso',
    items:['Pedido de credencial', 'Pedido de documento', 'Pedido de acesso remoto', 'Pedido de código'],
  },
]

/** @deprecated Use globalThreatPatternGroups — mantido para compatibilidade interna */
export const globalThreatPatterns = globalThreatPatternGroups.flatMap((group)=>group.items)

export function channelLabel(channel:string){
  const labels:Record<string,string> = {
    whatsapp: 'WhatsApp',
    sms: 'SMS',
    email: 'E-mail',
    phone: 'Telefone',
    telefone: 'Telefone',
    'browser popup': 'Pop-up do navegador',
    'pop-up do navegador': 'Pop-up do navegador',
    'social media': 'Rede social',
    'rede social': 'Rede social',
    'messaging app': 'App de mensagem',
    'app de mensagem': 'App de mensagem',
    'marketplace chat': 'Chat de marketplace',
    'chat de marketplace': 'Chat de marketplace',
  }
  return labels[channel] || channel
}

export function riskLevelLabel(level:string){
  if(level === 'critical') return 'crítico'
  if(level === 'high') return 'alto'
  if(level === 'medium') return 'médio'
  if(level === 'low') return 'baixo'
  return level
}
